### 덧셈 계산하기
GET http://localhost:8080/add?number1=100&number2=200
Accept: application/json

### 곱셈 계산하기
POST http://localhost:8080/multiply
Content-Type: application/json

{
  "number1": 10,
  "number2": 20
}



